// /frontend/src/constants/rolesAndPermissions.js

export const ROLES = Object.freeze({
  SUPERADMIN: 'superadmin',
  ADMIN: 'admin',
  MANAGER: 'manager',
  VENDEDOR: 'vendedor',
  WAREHOUSE: 'warehouse',
  ACCOUNTANT: 'accountant',
  HR_RECRUITER: 'hr_recruiter',
});

// --- Permisos de Módulos Principales (para menús de alto nivel) ---
export const CAN_ACCESS_SALES_MODULE = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.VENDEDOR];
export const CAN_ACCESS_PURCHASING_MODULE = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.WAREHOUSE, ROLES.ACCOUNTANT];
export const CAN_ACCESS_INVENTORY_MODULE = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.WAREHOUSE, ROLES.VENDEDOR];
export const CAN_ACCESS_FINANCE_MODULE = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.ACCOUNTANT];
export const CAN_ACCESS_HR_MODULE = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.HR_RECRUITER];
export const CAN_ACCESS_REPORTS_MODULE = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.VENDEDOR];
export const CAN_ACCESS_ADMIN_MODULE = [ROLES.SUPERADMIN, ROLES.ADMIN];

// --- Permisos Específicos por Acción ---
export const CAN_VIEW_SALES_DASHBOARD = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER];
export const CAN_MANAGE_CLIENTS = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.VENDEDOR];
export const CAN_MANAGE_QUOTES = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.VENDEDOR];
export const CAN_MANAGE_SALES_ORDERS = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.VENDEDOR];
export const CAN_USE_POS = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.VENDEDOR];
export const CAN_MANAGE_INVOICES = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.VENDEDOR];
export const CAN_MANAGE_RETURNS = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.VENDEDOR];

export const CAN_MANAGE_SUPPLIERS = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.WAREHOUSE, ROLES.MANAGER];
export const CAN_MANAGE_PURCHASE_ORDERS = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.WAREHOUSE, ROLES.MANAGER];
export const CAN_RECEIVE_GOODS = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.WAREHOUSE];
export const CAN_MANAGE_PAYABLES = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT];

export const CAN_MANAGE_PRODUCTS = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.WAREHOUSE, ROLES.MANAGER];
export const CAN_MANAGE_WAREHOUSES = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.WAREHOUSE];
export const CAN_CONTROL_STOCK = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.WAREHOUSE];
export const CAN_MANAGE_TRANSFERS = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.WAREHOUSE];
export const CAN_ADJUST_INVENTORY = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.WAREHOUSE, ROLES.MANAGER];
export const CAN_MANAGE_LOTS = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.WAREHOUSE];
export const CAN_VIEW_INVENTORY_VALUATION = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.MANAGER];

export const CAN_VIEW_FINANCE_DASHBOARD = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER];
export const CAN_MANAGE_RECEIVABLES = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT];

export const CAN_MANAGE_EMPLOYEES = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.HR_RECRUITER, ROLES.MANAGER];

export const CAN_GENERATE_CATALOG = [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.VENDEDOR];

export const ALL_ROLES = Object.freeze(Object.values(ROLES));

export const hasPermission = (allowedRoles, userRole) => {
  if (!userRole) return false;
  if (userRole === ROLES.SUPERADMIN) return true;
  return allowedRoles.includes(userRole);
};